# Generated by Django 3.1.3 on 2020-11-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=70)),
                ('content', models.TextField(max_length=5000)),
                ('time_stamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
