# Generated by Django 3.1.3 on 2020-11-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
